require "./bindings"

# =============================================================================
# Helper C bindings for OCF/IoTivity
# =============================================================================

@[Link(ldflags: "-I/home/pi/iot-lite/iotivity-lite -I/home/pi/iot-lite/iotivity-lite/include -I/home/pi/iot-lite/iotivity-lite/port/linux src/helper.c")]
lib Helper

  # =======================================================================================
  # C helper function bindings
  # =======================================================================================

  fun mmem_to_cstring(string : OC::String) : LibC::Char*

  # =======================================================================================
  # Device builder accessor variables
  # =======================================================================================

  # These are the global variables that need to be accessible from within Crystal
  # to allow for the use of the C code generated by IoTivity build tools.

  $pDevice : Void*
  $on_led_changed : -> Void
  $g_led_value : LibC::Int

  # =======================================================================================
  # Device builder function bindings
  # =======================================================================================

  fun initialize_variables() : Void
  fun app_init() : LibC::Int
  fun register_resources() : Void
  fun factory_presets_cb(device : LibC::SizeT, data : Void*) : Void

end
