require "./bindings"

# =============================================================================
# Helper C bindings for OCF/IoTivity
# =============================================================================

lib Helper

  # =======================================================================================
  # C helper function bindings
  # =======================================================================================

  fun mmem_to_cstring(string : OC::String) : LibC::Char*

  # =======================================================================================
  # Device builder accessor variables
  # =======================================================================================

  # These are the global variables that need to be accessible from within Crystal
  # to allow for the use of the C code generated by IoTivity build tools.

  $pClient : Void*
  $pServer : Void*

  # =======================================================================================
  # Device builder function bindings
  # =======================================================================================

  fun initialize_variables() : Void
  fun app_init() : LibC::Int
  fun register_resources() : Void
  fun factory_presets_cb(device : LibC::SizeT, data : Void*) : Void

  fun get_led(request : OC::Request*, interfaces : IoTivity::Interface, user_data : Void*) : Void
  fun post_led(request : OC::Request*, interfaces : IoTivity::Interface, user_data : Void*) : Void

end
